version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rewards
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A reward_project worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
